src/objects/Case__c.object
<CustomObject>
    <label>Case</label>
    <nameField>
        <displayFormat>Case - {0000000}</displayFormat>
        <label>Case</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Cases</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

src/objects/Court_Case__c.object
<CustomObject>
    <fields>
        <fullName>Case__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Case</label>
        <referenceTo>Case__c</referenceTo>
        <relationshipLabel>Related Court Cases</relationshipLabel>
        <relationshipName>Court_Cases</relationshipName>
        <type>Lookup</type>
    </fields>
    <label>Court Case</label>
    <nameField>
        <displayFormat>Court Case - {000000}</displayFormat>
        <label>Court Case ID</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Court Cases</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/objects/LASOResult__c.object
<CustomObject>
    <fields>
        <fullName>LinkToVPO__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>VPO</label>
        <referenceTo>VPO__c</referenceTo>
        <relationshipLabel>LASO Results</relationshipLabel>
        <relationshipName>LASO_Results</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Password__c</fullName>
        <label>Password</label>
        <length>100</length>
        <required>true</required>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Status__c</fullName>
        <label>Status</label>
        <length>1000</length>
        <type>LongTextArea</type>
    </fields>
    <fields>
        <fullName>UserName__c</fullName>
        <label>UserName</label>
        <length>100</length>
        <required>true</required>
        <type>Text</type>
    </fields>
    <label>LASO Result</label>
    <nameField>
        <displayFormat>{YYYYMMDD}-{0}</displayFormat>
        <label>LASO Result Id</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>LASO Results</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/objects/VPO__c.object
<CustomObject>
    <fields>
        <fullName>Court_Case__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Court Case</label>
        <referenceTo>Court_Case__c</referenceTo>
        <relationshipLabel>VPOs</relationshipLabel>
        <relationshipName>VPOs</relationshipName>
        <type>Lookup</type>
    </fields>
    <label>VPO</label>
    <nameField>
        <label>VPO Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>VPOs</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/classes/SubmitLASOCase.cls
public class SubmitLASOCase {
    @AuraEnabled
    public static string Submit(ID recordId){
        VPO__c vpo = [select Court_Case__r.Case__c from VPO__c where Id = :recordId];
        return new AnswerFileBuilder(recordId, new CallLASO()).SendCaseToLASO();
    }

    @AuraEnabled
    public static List<LASOResult__c> GetResults(Id recordId) {
        return [select id, UserName__c, Password__c, Status__c, CreatedDate
            from LASOResult__c
            where LinkToVPO__c = :recordId
            order by CreatedDate desc];
    }
}