src/objects/Case__c.object
<CustomObject>
    <label>Case</label>
    <nameField>
        <displayFormat>Case - {0000000}</displayFormat>
        <label>Case</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Cases</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

src/objects/LASOResult__c.object
<CustomObject>
    <fields>
        <fullName>LinkToVPO__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>VPO</label>
        <referenceTo>VPO__c</referenceTo>
        <relationshipLabel>LASO Results</relationshipLabel>
        <relationshipName>LASO_Results</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Password__c</fullName>
        <label>Password</label>
        <length>100</length>
        <required>true</required>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Status__c</fullName>
        <label>Status</label>
        <length>1000</length>
        <type>LongTextArea</type>
    </fields>
    <fields>
        <fullName>UserName__c</fullName>
        <label>UserName</label>
        <length>100</length>
        <required>true</required>
        <type>Text</type>
    </fields>
    <label>LASO Result</label>
    <nameField>
        <displayFormat>{YYYYMMDD}-{0}</displayFormat>
        <label>LASO Result Id</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>LASO Results</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/objects/LHIEndpoint__c.object
<CustomObject>
    <customSettingsType>List</customSettingsType>
    <fields>
        <fullName>Domain__c</fullName>
        <defaultValue>&quot;https://lhiutilitystage.lawhelpinteractive.org&quot;</defaultValue>
        <label>Domain</label>
        <length>50</length>
        <required>true</required>
        <type>Text</type>
    </fields>
    <label>LHI Endpoint</label>
</CustomObject>

src/objects/VPO__c.object
<CustomObject>
    <label>VPO</label>
    <nameField>
        <label>VPO Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>VPOs</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/classes/SubmitLASOCaseTest.cls
@isTest
public class SubmitLASOCaseTest {
    public static testmethod void CallsLASO() {
        insert new LHIEndpoint__c(Name = 'Default', Domain__c = 'test');
        FluentTester vault = new FluentTester();
        Case__c casen = vault.GetCase();
        insert new InformedConsent__c(LinkToCase__c=casen.Id);
        VPO__c vpo = vault.getVPO();

        Test.startTest();        
        ssos_UserActionsMock mock = Init();
        string result = SubmitLASOCase.Submit(vpo.Id);
        Test.stopTest();

        System.assertEquals('Success', result, 'result='+result);
        System.assert(mock != null);
    }

    public static testmethod void DoesNotCallLASOWithoutConsent() {
        insert new LHIEndpoint__c(Name = 'Default', Domain__c = 'test');
        FluentTester vault = new FluentTester();
        VPO__c vpo = vault.getVPO();

        Test.startTest();        
        ssos_UserActionsMock mock = Init();
        string result = SubmitLASOCase.Submit(vpo.Id);
        Test.stopTest();

        System.assertEquals('Cannot Submit without valid Informed Consent on file', result);
    }

    public static testmethod void DoesNotCallLASOWithExpiredConsent() {
        insert new LHIEndpoint__c(Name = 'Default', Domain__c = 'test');
        FluentTester vault = new FluentTester();
        Case__c casen = vault.GetCase();
        insert new InformedConsent__c(
            LinkToCase__c=casen.Id,
            DateExpires__c = System.today().addDays(-1)
            );
        VPO__c vpo = vault.getVPO();

        Test.startTest();        
        ssos_UserActionsMock mock = Init();
        string result = SubmitLASOCase.Submit(vpo.Id);
        Test.stopTest();

        System.assertEquals('Cannot Submit without valid Informed Consent on file', result);
    }

    public static testmethod void GetsResults() {
        FluentTester vault = new FluentTester();        
        VPO__c vpo = vault.getVPO();
        insert new LASOResult__c(
            LinkToVPO__c = vpo.Id,
            UserName__c = 'user',
            Password__c = 'pass',
            Status__c = 'status'
        );

        List<LASOResult__c> results = SubmitLASOCase.GetResults(vpo.Id);

        System.assertEquals(1, results.size());
        System.assertEquals('user', results[0].UserName__c);
        System.assertEquals('pass', results[0].Password__c);
        System.assertEquals('status', results[0].Status__c);
    }

    private static ssos_UserActionsMock Init() {
        
        ssos_UserActionsMock mock = new ssos_UserActionsMock();
        Test.setMock(WebServiceMock.class, mock);
        
        return mock;
    }
}