src/objects/Client__c.object
<CustomObject>
    <fields>
        <fullName>DOB__c</fullName>
        <label>Date of Birth</label>
        <required>true</required>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>FirstName__c</fullName>
        <label>First Name</label>
        <length>50</length>
        <required>true</required>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>LastName__c</fullName>
        <label>Last Name</label>
        <length>50</length>
        <required>true</required>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>SafeEmail__c</fullName>
        <description>A safe email address we can reach you at.</description>
        <inlineHelpText>A safe email address we can reach you at.</inlineHelpText>
        <label>Safe Email</label>
        <type>Email</type>
    </fields>
    <label>Client</label>
    <nameField>
        <displayFormat>Client -16- {000000}</displayFormat>
        <label>Client</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Clients</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/objects/LHIEndpoint__c.object
<CustomObject>
    <customSettingsType>List</customSettingsType>
    <fields>
        <fullName>Domain__c</fullName>
        <defaultValue>&quot;https://lhiutilitystage.lawhelpinteractive.org&quot;</defaultValue>
        <label>Domain</label>
        <length>50</length>
        <required>true</required>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>TemplateId__c</fullName>
        <defaultValue>4696</defaultValue>
        <label>Template Id</label>
        <precision>10</precision>
        <scale>0</scale>
        <required>true</required>
        <type>Number</type>
    </fields>
    <label>LHI Endpoint</label>
</CustomObject>

src/classes/CallLASOTest.cls
@isTest
public class CallLASOTest {
    public static testmethod void InitializesClass() {
        insert new LHIEndpoint__c(Name = 'Default', Domain__c = 'test');
        CallLASO testee = new CallLASO();
        testee.GetLoginInfo(new Client__c(
            FirstName__c = 'Test',
            LastName__c = 'Client',            
            DOB__c = Date.newInstance(1990,1,1)
        ));

        ssos_AnswerFile.User_x mocked = Init(testee);

        System.assertEquals('test', mocked.AnswerFile);
    }

    public static testmethod void CreatesUser() {
        insert new LHIEndpoint__c(Name = 'Default', Domain__c = 'test');
        CallLASO testee = new CallLASO();
        testee.GetLoginInfo(new Client__c(
            FirstName__c = 'Test',
            LastName__c = 'Client',
            SafeEmail__c = 'default@default.default',
            DOB__c = Date.newInstance(1990,1,1)
        ));

        ssos_AnswerFile.User_x mocked = Init(testee);

        System.assert(mocked.UserName.contains('tclient'));
        System.assertEquals('Test', mocked.FirstName);
        System.assertEquals('Client', mocked.LastName);
        System.assertEquals('vpo@palomarokc.org', mocked.Email);
        System.assertEquals(37, mocked.StateId);
        System.assertEquals(1, mocked.UserTypeId);
        System.assertEquals(1, mocked.SecurityQuestionId);
        System.assertEquals('Palomar', mocked.SecurityAnswer);
        System.assertEquals(
            Integer.valueOf(LHIEndpoint__c.getValues('Default').TemplateId__c), 
            mocked.TemplateId);
    }

    public static testmethod void ReturnsLASOLoginInfo() {
        insert new LHIEndpoint__c(Name = 'Default', Domain__c = 'test');
        CallLASO testee = new CallLASO();
        Map<String, String> loginInfo = testee.GetLoginInfo(new Client__c(
            FirstName__c = 'Test',
            LastName__c = 'Client',
            DOB__c = Date.newInstance(1990,1,1)
        ));

        System.assert(loginInfo.get('username').contains('tclient'));
        System.assert(loginInfo.get('password').length() >= 8);
    }

    private static ssos_AnswerFile.User_x Init(CallLASO testee) {        
        ssos_UserActionsMock mock = new ssos_UserActionsMock();
        Test.setMock(WebServiceMock.class, mock);        

        Test.startTest();
        List<string> result = testee.SaveDocument('test');
        Test.stopTest();
        
        return mock.incoming.user_x;
    }
}